### ISSUE TITLE
How can I improve this repository?

### ISSUE THREAD

**Issue by irakrakow** [irakrakow/CS50W-2020#1]
My initial idea is just for myself, to help me follow along with Brian's lectures by entering and running the source code, embedded in the notes for each of Brian's lectures, for example [notes for Lecture 0](https://cs50.harvard.edu/web/2020/notes/0/), using Microsoft's VSCode, so that instead of trying to code as Brian delivers his lecture, I can just follow along with the code already written.  I'm finding that this approach really helps me to absorb Brian's amazing insights faster. 

I'm wondering...would this help you as well?  I welcome all suggestions.

Ira

#cs50  #cs50w #harvard #web-programming

**Comment by rukundob451** [comment]
Hello @irakrakow, can I work on this?

**Comment by irakrakow** [comment]
@rukundob451 Sure! Please review what I've done so far, [fork the repo]( https://github.com/irakrakow/CS50W-2020.git), and give me your thoughts.  This will help both of us.  Then we can decide what makes the most sense.  Thanks!

**Comment by rukundob451** [comment]
Hey Irakrakow, going to fork it and tell you what I think about it.

Thank you,

Benjamin.

**Comment by irakrakow** [comment]
Hey Benjamin!  Looking forward to your comments!

Thank you.

IRA

**Comment by irakrakow** [comment]
Looks good!
